[package]
name = "controller"
version = "0.1.0"
authors = ["talbor49 <talbor49@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustdoor = { path = "c:\\dev\\rustdoor" }
ron = "0.5.1"
byteorder = "1.3.2"
